#!/usr/bin/env bash
# Bash script that transfers file from client to server

#check for command line arguments
if [ $# -lt 4 ]
then
        echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
        exit 1
fi

# Assigning parameters to variables

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Disable strict host key checking using scp
scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Validating file transfer
if [ $? -eq 0 ]
then
        echo "TRANSFER SUCCESSFUL"
else
        echo "FILE TRANSFER FAILED"
fi
