#!/usr/bin/env bash
# Create a custom 404 not found page

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

string_to_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Emmanuelmshindi permanent;"

sudo sed -i "s/server_name _;/$string_to_replace/" /etc/nginx/sites-enabled/default

# Create the 404 error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var/www/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
